# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kx-blpBtAZ5R0Mi2Z57Ic59gOZWRJ1TK
"""

from fastapi import FastAPI
from backend.recommender import get_recommendations

app = FastAPI(
    title="Retail Recommendation API"
)

@app.get("/")
def home():
    return {"message": "API Running"}

@app.get("/recommend")
def recommend(product: str):

    recommendations = get_recommendations(product)

    return {
        "product": product,
        "recommendations": recommendations
    }