# -*- coding: utf-8 -*-
"""recommender.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pac2gZu2C0Yzv6ppYA8lD_dToQmN3SV-
"""



import pandas as pd
from apyori import apriori

# Load dataset
dataset = pd.read_excel("data/Online Retail.xlsx")


# Preprocessing
dataset = dataset[['InvoiceNo', 'Description', 'Quantity']]

dataset = dataset[
    ~dataset['InvoiceNo'].astype(str).str.contains('C')
]

dataset = dataset.dropna(subset=['Description'])

dataset = dataset[dataset['Quantity'] > 0]

# Create transactions
transactions = (
    dataset.groupby('InvoiceNo')['Description']
    .apply(list)
    .tolist()
)

# Train Apriori
rules = list(apriori(
    transactions=transactions,
    min_support=0.003,
    min_confidence=0.2,
    min_lift=3,
    min_length=2,
    max_length=2
))


# Recommendation function
def get_recommendations(product_name):

    recommendations = []

    for item in rules:

        pair = item[2][0]

        lhs = list(pair[0])
        rhs = list(pair[1])

        if product_name in lhs:
            recommendations.extend(rhs)

    return list(set(recommendations))